spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 123456
    password: 123456
    url: jdbc:mysql://111.230.245.121:3306/springcloud_product?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
PRODUCT-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env: dev10
